alias:deny("cancel")
alias:enter("exit", "en", "ex")
alias:items("item", "inv", "inventory")
alias:email("mail")
alias:savestats("savestat", "saveme")
alias:time("delay")
alias:clearchat("cc")
alias:destroyveh("respawnallpv")
alias:openvehiclemenu("staticveh")
alias:fixcp("destroycp")
alias:myproperty("mp")